int redPin=13;
int greenPin=2;
int bluePin=3;

int redBlink=100;
int greenBlink=200;
int blueBlink=400;

void setup() {
  // put your setup code here, to run once:
pinMode(redPin, OUTPUT);
pinMode(greenPin, OUTPUT);
pinMode(bluePin, OUTPUT);
}

void loop() {
  // put your main code here, to run repeatedly:
digitalWrite(redPin, HIGH);
delay(redBlink);
digitalWrite(redPin,LOW);
delay(redBlink);
digitalWrite(redPin, HIGH);
delay(redBlink);
digitalWrite(redPin,LOW);
delay(redBlink);
digitalWrite(redPin, HIGH);
delay(redBlink);
digitalWrite(redPin,LOW);
delay(redBlink);
digitalWrite(redPin, HIGH);
delay(redBlink);
digitalWrite(redPin,LOW);
delay(redBlink);
digitalWrite(redPin, HIGH);
delay(redBlink);
digitalWrite(redPin,LOW);
delay(redBlink);

digitalWrite(greenPin, HIGH);
delay(greenBlink);
digitalWrite(greenPin,LOW);
delay(greenBlink);
digitalWrite(greenPin, HIGH);
delay(greenBlink);
digitalWrite(greenPin,LOW);
delay(greenBlink);
digitalWrite(greenPin, HIGH);
delay(greenBlink);
digitalWrite(greenPin,LOW);
delay(greenBlink);
digitalWrite(greenPin, HIGH);
delay(greenBlink);
digitalWrite(greenPin,LOW);
delay(greenBlink);
digitalWrite(greenPin, HIGH);
delay(greenBlink);
digitalWrite(greenPin,LOW);
delay(greenBlink);
digitalWrite(greenPin, HIGH);
delay(greenBlink);
digitalWrite(greenPin,LOW);
delay(greenBlink);
digitalWrite(greenPin, HIGH);
delay(greenBlink);
digitalWrite(greenPin,LOW);
delay(greenBlink);
digitalWrite(greenPin, HIGH);
delay(greenBlink);
digitalWrite(greenPin,LOW);
delay(greenBlink);
digitalWrite(greenPin, HIGH);
delay(greenBlink);
digitalWrite(greenPin,LOW);
delay(greenBlink);
digitalWrite(greenPin, HIGH);
delay(greenBlink);
digitalWrite(greenPin,LOW);
delay(greenBlink);

digitalWrite(bluePin, HIGH);
delay(blueBlink);
digitalWrite(bluePin,LOW);
delay(blueBlink);
digitalWrite(bluePin, HIGH);
delay(blueBlink);
digitalWrite(bluePin,LOW);
delay(blueBlink);
digitalWrite(bluePin, HIGH);
delay(blueBlink);
digitalWrite(bluePin,LOW);
delay(blueBlink);
digitalWrite(bluePin, HIGH);
delay(blueBlink);
digitalWrite(bluePin,LOW);
delay(blueBlink);
digitalWrite(bluePin, HIGH);
delay(blueBlink);
digitalWrite(bluePin,LOW);
delay(blueBlink);
digitalWrite(bluePin, HIGH);
delay(blueBlink);
digitalWrite(bluePin,LOW);
delay(blueBlink);
digitalWrite(bluePin, HIGH);
delay(blueBlink);
digitalWrite(bluePin,LOW);
delay(blueBlink);
digitalWrite(bluePin, HIGH);
delay(blueBlink);
digitalWrite(bluePin,LOW);
delay(blueBlink);
digitalWrite(bluePin, HIGH);
delay(blueBlink);
digitalWrite(bluePin,LOW);
delay(blueBlink);
digitalWrite(bluePin, HIGH);
delay(blueBlink);
digitalWrite(bluePin,LOW);
delay(blueBlink);
digitalWrite(bluePin, HIGH);
delay(blueBlink);
digitalWrite(bluePin,LOW);
delay(blueBlink);
digitalWrite(bluePin, HIGH);
delay(blueBlink);
digitalWrite(bluePin,LOW);
delay(blueBlink);
digitalWrite(bluePin, HIGH);
delay(blueBlink);
digitalWrite(bluePin,LOW);
delay(blueBlink);
digitalWrite(bluePin, HIGH);
delay(blueBlink);
digitalWrite(bluePin,LOW);
delay(blueBlink);
digitalWrite(bluePin, HIGH);
delay(blueBlink);
digitalWrite(bluePin,LOW);
delay(blueBlink);
}
